name: spotify
description: A dart library for interfacing with the Spotify API.
version: 0.1.0
homepage: https://github.com/rinukkusu/spotify-dart
authors:
- rinukkusu <rinukkusu@auen.land>
- Chance Snow <git@chancesnow.me>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  json_annotation: ^2.0.0

dev_dependencies:
  test: ^1.5.1
  build_runner: ^1.1.1
  json_serializable: ^2.0.0
